apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: appfastfood-pagamentos-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: appfastfood-pagamentos-deployment
  minReplicas: 1
  maxReplicas: 4
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30 # Tempo de espera antes de escalar para baixo
    scaleUp:
      stabilizationWindowSeconds: 10 # Tempo de espera antes de escalar para cima
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: 200m
